services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
    volumes:
      - postgres_data:/var/lib/postgres/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - 8001:8978 # CloudBeaver mapped to localhost:8001
    depends_on:
      - postgres

volumes:
  postgres_data:
